# Generated by Django 4.0.2 on 2022-02-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_date', models.DateTimeField(auto_now=True)),
                ('exp_cat', models.CharField(max_length=10)),
                ('exp_sum', models.IntegerField()),
                ('exp_cash', models.IntegerField()),
                ('exp_text', models.CharField(max_length=200)),
            ],
        ),
    ]
