# Generated by Django 4.0.2 on 2022-02-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='exp_cash',
            field=models.IntegerField(verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='exp_cat',
            field=models.CharField(max_length=10, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='exp_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='exp_sum',
            field=models.IntegerField(verbose_name='Потраченная сумма'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='exp_text',
            field=models.CharField(max_length=200, verbose_name='Примечание'),
        ),
    ]
