# Generated by Django 4.0.2 on 2022-02-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_expense_exp_cash_alter_expense_exp_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='exp_cash',
        ),
    ]
