# Generated by Django 4.0.2 on 2022-02-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_expense_exp_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_wallet', models.IntegerField(verbose_name='Остаток')),
            ],
        ),
    ]
